# Generated by Django 5.1.1 on 2024-10-09 01:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloLogin', '0015_alter_empleado__annos_experiencia'),
        ('modulo_evento', '0027_cliente'),
        ('modulo_stock', '0009_remitoproveedor__empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
            },
        ),
        migrations.CreateModel(
            name='TipoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo Factura',
                'verbose_name_plural': 'Tipos Factura',
            },
        ),
        migrations.CreateModel(
            name='FacturaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_numero_factura', models.CharField(max_length=100, unique=True, verbose_name='Número de Factura')),
                ('_fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('_precio_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Precio Total')),
                ('_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.cliente', verbose_name='Cliente')),
                ('_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.empleado', verbose_name='Empleado')),
                ('_medio_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ventas.mediodepago', verbose_name='Medio de pago')),
                ('_tipo_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ventas.tipofactura', verbose_name='Tipo Factura')),
            ],
            options={
                'verbose_name': 'Factura (Cliente)',
                'verbose_name_plural': 'Facturas (Cliente)',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('_precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('_subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ventas.facturacliente', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle Factura (Cliente)',
                'verbose_name_plural': 'Detalle Factura (Cliente)',
            },
        ),
        migrations.CreateModel(
            name='DetalleArticulo',
            fields=[
                ('detallefactura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modulo_ventas.detallefactura')),
                ('_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.articulo')),
            ],
            options={
                'verbose_name': 'Detalle Articulo',
                'verbose_name_plural': 'Detalle Articulo',
            },
            bases=('modulo_ventas.detallefactura',),
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('detallefactura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modulo_ventas.detallefactura')),
                ('_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.entrada', verbose_name='Entrada')),
            ],
            options={
                'verbose_name': 'Detalle Entrada',
                'verbose_name_plural': 'Detalle Entrada',
            },
            bases=('modulo_ventas.detallefactura',),
        ),
        migrations.CreateModel(
            name='DetalleReservacion',
            fields=[
                ('detallefactura_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modulo_ventas.detallefactura')),
                ('_reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.mesa')),
            ],
            options={
                'verbose_name': 'Detalle de Reservación',
                'verbose_name_plural': 'Detalle de Reservación',
            },
            bases=('modulo_ventas.detallefactura',),
        ),
    ]
