# Generated by Django 5.1.1 on 2024-10-10 02:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0027_cliente'),
        ('modulo_stock', '0009_remitoproveedor__empleado'),
        ('modulo_ventas', '0002_alter_facturacliente__cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallearticulo',
            options={'verbose_name': 'Detalle de Bebida', 'verbose_name_plural': 'Detalles de Bebida'},
        ),
        migrations.AlterModelOptions(
            name='detalleentrada',
            options={'verbose_name': 'Detalle de Entrada', 'verbose_name_plural': 'Detalles de Entrada'},
        ),
        migrations.AlterField(
            model_name='detallearticulo',
            name='_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.articulo', verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='_precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='detallereservacion',
            name='_reservacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.mesa', verbose_name='Reservación'),
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='_precio_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Total'),
        ),
    ]
