# Generated by Django 5.1.1 on 2024-10-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0003_alter_detallearticulo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_monto_usdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_estado', models.CharField(max_length=20)),
                ('_detalles_pago', models.TextField(blank=True, null=True)),
                ('_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('_fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ventas.facturacliente')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
            },
        ),
    ]
