# Generated by Django 5.1.1 on 2024-10-17 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0015_alter_empleado__annos_experiencia'),
        ('modulo_ventas', '0005_facturacliente__pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccionpago',
            name='_detalles_pago',
        ),
        migrations.RemoveField(
            model_name='transaccionpago',
            name='_estado',
        ),
        migrations.RemoveField(
            model_name='transaccionpago',
            name='_fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='transaccionpago',
            name='_monto_usdt',
        ),
        migrations.AddField(
            model_name='transaccionpago',
            name='_qr_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del QR'),
        ),
        migrations.AlterField(
            model_name='transaccionpago',
            name='_factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_pago', to='modulo_ventas.facturacliente'),
        ),
        migrations.AlterField(
            model_name='transaccionpago',
            name='_fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='facturacliente',
            unique_together={('_empleado', '_numero_factura')},
        ),
    ]
