# Generated by Django 5.1.1 on 2024-10-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0006_remove_transaccionpago__detalles_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionpago',
            name='_qr_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
