# Generated by Django 5.1.1 on 2024-10-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_clientes', '0001_initial'),
        ('modulo_ventas', '0007_transaccionpago__qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacliente',
            name='_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_clientes.cliente', verbose_name='Cliente'),
        ),
    ]
