# Generated by Django 5.1.1 on 2024-10-30 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0015_alter_empleado__annos_experiencia'),
        ('modulo_ventas', '0008_alter_facturacliente__cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacliente',
            name='_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.empleado', verbose_name='Empleado'),
        ),
    ]
