# Generated by Django 5.1 on 2024-09-13 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='_ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.ubicacion', verbose_name='Ubicación'),
        ),
    ]
