# Generated by Django 5.1 on 2024-09-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0002_alter_evento__ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='_ubicacion',
        ),
    ]
