# Generated by Django 5.1 on 2024-09-14 16:20

import mapbox_location_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0003_remove_evento__ubicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.AddField(
            model_name='evento',
            name='_coordenadas',
            field=mapbox_location_field.models.LocationField(default='-26.1849,-58.1731', map_attrs={'center': [-26.1849, -58.1731], 'style': 'mapbox://styles/maptiler/streets-v11', 'zoom': 10}),
        ),
    ]
