# Generated by Django 5.1 on 2024-09-14 17:47

import mapbox_location_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0004_delete_ubicacion_evento__coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='_coordenadas',
            field=mapbox_location_field.models.LocationField(default='-26.1849,-58.1731', map_attrs={'center': [-26.1849, -58.1731], 'style': 'https://api.maptiler.com/maps/streets/style.json?key=HhZs7tN2CwC4JrhbLLTL', 'zoom': 10}),
        ),
    ]
