# Generated by Django 5.1 on 2024-09-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0005_alter_evento__coordenadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='_coordenadas',
        ),
        migrations.AddField(
            model_name='fiesta',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiesta',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
