# Generated by Django 5.1 on 2024-09-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0006_remove_evento__coordenadas_fiesta_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='_latitud',
            field=models.DecimalField(decimal_places=6, default=-26.1849, max_digits=9),
        ),
        migrations.AddField(
            model_name='evento',
            name='_longitud',
            field=models.DecimalField(decimal_places=6, default=-58.1731, max_digits=9),
        ),
    ]
