# Generated by Django 5.1 on 2024-09-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0007_evento__latitud_evento__longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiesta',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='fiesta',
            name='longitud',
        ),
    ]
