# Generated by Django 5.1 on 2024-09-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0008_remove_fiesta_latitud_remove_fiesta_longitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='_latitud',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='_longitud',
            new_name='longitud',
        ),
    ]
