# Generated by Django 5.1 on 2024-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0010_alter_evento_latitud_alter_evento_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='_descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='_edad_maxima',
            field=models.PositiveIntegerField(default=40, verbose_name='Edad máxima'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='_edad_minima',
            field=models.PositiveIntegerField(default=18, verbose_name='Edad mínima'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='latitud',
            field=models.DecimalField(decimal_places=4, default=-26.1855, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitud',
            field=models.DecimalField(decimal_places=4, default=-58.1739, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fiesta',
            name='_categoria',
            field=models.CharField(choices=[('Tematica', 'Temática'), ('Electronica', 'Electrónica'), ('Reggaeton', 'Reggaetón'), ('Pop & Hits', 'Pop & Hits'), ('Latino', 'Latino'), ('Trap', 'Trap'), ('Fiesta Retro', 'Fiesta Retro'), ('VIP Exclusive', 'VIP Exclusive')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='fiesta',
            name='_vestimenta',
            field=models.CharField(choices=[('Formal', 'Formal'), ('Casual', 'Casual'), ('Streetwear', 'Streetwear'), ('Disfraz Tematico', 'Disfraz Temático')], max_length=20, verbose_name='Vestimenta'),
        ),
    ]
