# Generated by Django 5.1.1 on 2024-09-19 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0015_alter_empleado__annos_experiencia'),
        ('modulo_evento', '0012_evento__fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.persona')),
                ('_embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
            bases=('moduloLogin.persona',),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_categoria', models.CharField(choices=[('Popular', 'Popular'), ('VIP', 'VIP')], max_length=20, verbose_name='Categoría')),
                ('_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.cliente', verbose_name='Cliente')),
                ('_fiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.fiesta', verbose_name='Fiesta')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_capacidad', models.PositiveIntegerField(default=1, verbose_name='Capacidad')),
                ('_categoria', models.CharField(choices=[('Popular', 'Popular'), ('VIP', 'VIP')], max_length=20, verbose_name='Categoría')),
                ('_disponibilidad', models.BooleanField(default=True)),
                ('_fiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.fiesta', verbose_name='Fiesta')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
    ]
