# Generated by Django 5.1.1 on 2024-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0013_cliente_entrada_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiesta',
            name='_publicada',
            field=models.BooleanField(default=False, verbose_name='Publicada'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='_capacidad',
            field=models.PositiveIntegerField(default=8, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='_disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Disponibilidad'),
        ),
    ]
