# Generated by Django 5.1.1 on 2024-09-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0015_mesa__left_mesa__top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='_disponibilidad',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='_left',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='_top',
        ),
    ]
