# Generated by Django 5.1.1 on 2024-09-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0017_mesa_disponibilidad_mesa_left_mesa_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='disponibilidad',
            new_name='_disponibilidad',
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='left',
            new_name='_left',
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='top',
            new_name='_top',
        ),
    ]
