# Generated by Django 5.1.1 on 2024-09-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0018_rename_disponibilidad_mesa__disponibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiesta',
            name='_publicada',
        ),
    ]
