# Generated by Django 5.1.1 on 2024-09-26 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0020_alter_mesa__left_alter_mesa__top'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='_precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
        migrations.AddField(
            model_name='fiesta',
            name='_cantidad_entrada_popular',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Entradas Populares'),
        ),
        migrations.AddField(
            model_name='fiesta',
            name='_cantidad_entrada_vip',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Entradas VIP'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
    ]
