# Generated by Django 5.1.1 on 2024-09-26 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0021_entrada__precio_unitario_and_more'),
        ('modulo_stock', '0008_alter_movimientostock__cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaTieneArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.articulo', verbose_name='Bebida')),
                ('_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_evento.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Gestión de Mesas',
                'verbose_name_plural': 'Gestión de Mesas',
            },
        ),
    ]
