# Generated by Django 5.1.1 on 2024-09-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0024_movimientofiesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientofiesta',
            options={'ordering': ['-_fecha', '-_fiesta___fecha', '_fiesta___nombre', '_administrador___nombre', '_administrador___apellido'], 'verbose_name': 'Movimientos de Fiestas', 'verbose_name_plural': 'Movimientos de Fiestas'},
        ),
        migrations.AlterField(
            model_name='movimientofiesta',
            name='_descripcion',
            field=models.CharField(max_length=300, verbose_name='Descripción'),
        ),
    ]
