# Generated by Django 5.1.1 on 2024-10-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0025_alter_movimientofiesta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='_cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
