# Generated by Django 5.1.1 on 2024-10-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_evento', '0027_cliente'),
        ('modulo_ventas', '0008_alter_facturacliente__cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
