# Generated by Django 5.1 on 2024-09-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloLogin', '0007_alter_auditor__frecuencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nombre', models.CharField(max_length=100)),
                ('_volumen', models.DecimalField(decimal_places=2, help_text='Volumen en mililitros', max_digits=5)),
                ('_precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_stock', models.PositiveIntegerField()),
                ('_stock_minimo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.persona')),
                ('_condicion_iva', models.CharField(choices=[('Responsable Inscripto', 'Responsable Inscripto'), ('Monotributista', 'Monotributista'), ('Exento', 'Exento')], default='Responsable Inscripto', max_length=50)),
            ],
            bases=('moduloLogin.persona',),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('articulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modulo_stock.articulo')),
                ('_marca', models.CharField(max_length=100)),
            ],
            bases=('modulo_stock.articulo',),
        ),
        migrations.CreateModel(
            name='Trago',
            fields=[
                ('articulo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modulo_stock.articulo')),
                ('_tipo', models.CharField(choices=[('Cóctel', 'Cóctel'), ('Shot', 'Shot'), ('Licuado', 'Licuado')], max_length=50)),
            ],
            bases=('modulo_stock.articulo',),
        ),
        migrations.CreateModel(
            name='RemitoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fecha_emision_remito', models.DateField()),
                ('_numero_remito', models.CharField(max_length=100)),
                ('_id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_cantidad', models.PositiveIntegerField()),
                ('_fecha_movimiento', models.DateField()),
                ('_id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.empleado')),
                ('_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRemitoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_cantidad', models.PositiveIntegerField()),
                ('_fecha_entrega_producto', models.DateField()),
                ('_id_remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.remitoproveedor')),
                ('_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_cantidad_producto', models.DecimalField(decimal_places=2, help_text='Volumen en mililitros', max_digits=5)),
                ('_id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.producto')),
                ('_id_trago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_stock.trago')),
            ],
        ),
    ]
