# Generated by Django 5.1 on 2024-09-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_stock', '0004_marca_alter_articulo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricacion',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Elaboración'},
        ),
        migrations.AlterField(
            model_name='fabricacion',
            name='_cantidad_producto',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cantidad  (mililitros)'),
        ),
    ]
