# Generated by Django 5.1 on 2024-09-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_stock', '0007_alter_articulo__stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientostock',
            name='_cantidad',
            field=models.IntegerField(verbose_name='Cantidad (+-)'),
        ),
        migrations.AlterUniqueTogether(
            name='remitoproveedor',
            unique_together={('_proveedor', '_numero_remito')},
        ),
    ]
