# Generated by Django 5.1 on 2024-08-30 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_dni', models.CharField(max_length=20, unique=True)),
                ('_cuil', models.CharField(max_length=20, unique=True)),
                ('_nombre', models.CharField(max_length=100)),
                ('_apellido', models.CharField(max_length=100)),
                ('_fecha_nacimiento', models.DateField()),
                ('_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_hora_inicio', models.TimeField()),
                ('_hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.persona')),
                ('_zona_asignada', models.CharField(choices=[('Planta baja', 'Planta baja'), ('Primer piso', 'Primer piso')], max_length=100)),
                ('_sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('_estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=50)),
                ('_telefono', models.CharField(max_length=50)),
                ('_fecha_inicio', models.DateField()),
                ('_seniority', models.CharField(choices=[('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=50)),
                ('_annos_experiencia', models.PositiveIntegerField()),
            ],
            bases=('moduloLogin.persona',),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('_frecuencia', models.PositiveIntegerField()),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('_barra_asignada', models.CharField(max_length=100)),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('_caja_asignada', models.CharField(max_length=100)),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Mozo',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('_entrada_asignada', models.CharField(max_length=100)),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('_frecuencia', models.PositiveIntegerField()),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='EmpleadoTieneTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.turno')),
                ('_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_fecha_contratacion', models.DateField(default=django.utils.timezone.now)),
                ('_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones', to='moduloLogin.empleado')),
                ('_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones_administradas', to='moduloLogin.administrador')),
            ],
        ),
    ]
