# Generated by Django 5.1 on 2024-08-29 15:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('cuil', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.persona')),
                ('zona_asignada', models.CharField(choices=[('Planta baja', 'Planta baja'), ('Primer piso', 'Primer piso')], max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('seniority', models.CharField(choices=[('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=50)),
                ('annos_experiencia', models.PositiveIntegerField()),
            ],
            bases=('moduloLogin.persona',),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('cantidad_empleados_contratados', models.IntegerField(default=0)),
                ('cantidad_fiestas_organizadas', models.IntegerField(default=0)),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('frecuencia', models.PositiveIntegerField()),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('barra_asignada', models.CharField(max_length=100)),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('caja_asignada', models.CharField(max_length=100)),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Mozo',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('entrada_asignada', models.CharField(max_length=100)),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moduloLogin.empleado')),
                ('frecuencia', models.PositiveIntegerField()),
            ],
            bases=('moduloLogin.empleado',),
        ),
        migrations.CreateModel(
            name='EmpleadoTieneTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.turno')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones', to='moduloLogin.empleado')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones_administradas', to='moduloLogin.administrador')),
            ],
        ),
    ]
