# Generated by Django 5.1 on 2024-09-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0003_alter_empleado__estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadotieneturno',
            options={'verbose_name': 'Asignación de Turno'},
        ),
    ]
