# Generated by Django 5.1 on 2024-09-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0004_alter_empleadotieneturno_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='_telefono',
        ),
        migrations.AddField(
            model_name='persona',
            name='_domicilio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
