# Generated by Django 5.1 on 2024-09-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0005_remove_empleado__telefono_persona__domicilio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='_domicilio',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='_telefono',
        ),
    ]
