# Generated by Django 5.1 on 2024-09-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('moduloLogin', '0009_alter_auditor__frecuencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('_numero', models.PositiveBigIntegerField(verbose_name='Número')),
                ('_codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='Ciudad')),
                ('_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='País')),
                ('_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.persona', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
    ]
