# Generated by Django 5.1 on 2024-09-12 16:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0011_remove_domicilio__pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_numero_telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Número de Teléfono')),
                ('_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloLogin.persona', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
            },
        ),
    ]
