# Generated by Django 5.1.1 on 2024-09-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0012_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacion',
            name='_tipo',
            field=models.CharField(choices=[('Contratacion', 'Contratacion'), ('Renovacion', 'Renovacion'), ('Despido', 'Despido')], max_length=50, verbose_name='Tipo'),
        ),
    ]
