# Generated by Django 5.1.1 on 2024-09-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloLogin', '0013_alter_contratacion__tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='_annos_experiencia',
            field=models.PositiveBigIntegerField(verbose_name='Años de experiencia'),
        ),
    ]
